/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonebook;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static phonebook.First.xx;

/**
 *
 * @author HP
 */
public class AddFrame extends javax.swing.JFrame {
        private String phoneNumber;
	private Contact contact = new Contact();
	private int number;
	private String gender = "Male";
	private String type = "Personal";
    /**
     * Creates new form AddFrame
     */
    public AddFrame() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLFrameName = new javax.swing.JLabel();
        jLEmail = new javax.swing.JLabel();
        jLLastName = new javax.swing.JLabel();
        jLFirstName = new javax.swing.JLabel();
        jLAddress = new javax.swing.JLabel();
        jLPhoneNumber = new javax.swing.JLabel();
        jLGender = new javax.swing.JLabel();
        jLContactType = new javax.swing.JLabel();
        tfFirstName = new javax.swing.JTextField();
        tfLastName = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        tfNumber = new javax.swing.JTextField();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jcType = new javax.swing.JComboBox();
        jcAreaCode = new javax.swing.JComboBox();
        jbSave = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLExitSign = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLMinimizeSign = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLFrameName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLFrameName.setForeground(new java.awt.Color(255, 153, 0));
        jLFrameName.setText("Add Contact");

        jLEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLEmail.setForeground(new java.awt.Color(204, 255, 255));
        jLEmail.setText("Email");

        jLLastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLLastName.setForeground(new java.awt.Color(204, 255, 255));
        jLLastName.setText("Last Name");

        jLFirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLFirstName.setForeground(new java.awt.Color(204, 255, 255));
        jLFirstName.setText("First Name");

        jLAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLAddress.setForeground(new java.awt.Color(204, 255, 255));
        jLAddress.setText("Address");

        jLPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLPhoneNumber.setForeground(new java.awt.Color(204, 255, 255));
        jLPhoneNumber.setText("Phone Number");

        jLGender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLGender.setForeground(new java.awt.Color(204, 255, 255));
        jLGender.setText("Gender");

        jLContactType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLContactType.setForeground(new java.awt.Color(204, 255, 255));
        jLContactType.setText("Contact Type");

        tfNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        rbMale.setBackground(new java.awt.Color(102, 102, 102));
        rbMale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbMale.setForeground(new java.awt.Color(204, 255, 255));
        rbMale.setSelected(true);
        rbMale.setText("Male");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });

        rbFemale.setBackground(new java.awt.Color(102, 102, 102));
        rbFemale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbFemale.setForeground(new java.awt.Color(204, 255, 255));
        rbFemale.setText("Female");
        rbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemaleActionPerformed(evt);
            }
        });

        jcType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personal", "Work" }));

        jcAreaCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcAreaCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "050", "052", "053", "054", "03", "04", "08", "09" }));

        jbSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbSave.setText("Save");
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        jbCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbCancel.setText("Reset");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(15, 25));

        jLExitSign.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLExitSign.setForeground(new java.awt.Color(153, 255, 255));
        jLExitSign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLExitSign.setText("x");
        jLExitSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLExitSignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLExitSignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLExitSignMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLExitSign, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLExitSign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setAlignmentX(0.1F);
        jPanel4.setAlignmentY(0.1F);
        jPanel4.setPreferredSize(new java.awt.Dimension(32, 33));

        jLMinimizeSign.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLMinimizeSign.setForeground(new java.awt.Color(153, 255, 255));
        jLMinimizeSign.setText("_");
        jLMinimizeSign.setAlignmentX(0.1F);
        jLMinimizeSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLMinimizeSign, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLMinimizeSign)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLFrameName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLContactType, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLGender, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rbMale, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcAreaCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jbSave, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(358, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(331, 331, 331)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLFrameName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLGender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbMale)
                    .addComponent(rbFemale))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLContactType, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcAreaCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSave)
                    .addComponent(jbCancel))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(467, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(467, Short.MAX_VALUE)))
        );

        tfFirstName.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void setColor(JPanel p)
        {
            p.setBackground(new Color(255,0,0));
        }
    public void resetColor(JPanel p1)
        {
            p1.setBackground(new Color(102,102,102));
        }
    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        if (rbMale.isSelected())
        {
            gender = "Male";
            rbFemale.setSelected(false);
        }
    }//GEN-LAST:event_rbMaleActionPerformed

    private void rbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemaleActionPerformed
        if (rbFemale.isSelected())
        {
            gender = "Female";
            rbMale.setSelected(false);
        }
    }//GEN-LAST:event_rbFemaleActionPerformed

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        //save contact info and add it to contacts array
        boolean found=false;
       boolean checkPhone;
       ImageIcon icon = new ImageIcon(getClass().getResource("phoneIcon.png"));
        ArrayList<Contact> list = ContactListSingelton.getInstance().getArray();
        if(tfFirstName.getText().isEmpty() || tfLastName.getText().isEmpty() || tfEmail.getText().isEmpty()
						|| tfNumber.getText().isEmpty())
            {
                int check = JOptionPane.showConfirmDialog(null, "Some of the fields are empty, are you sure you want to continue?","Add",JOptionPane.YES_NO_OPTION);
                if (check == 0) //checks the return answer of the user if to continue with saving the contact
                {
                    phoneNumber = jcAreaCode.getSelectedItem() + tfNumber.getText() ;
                    checkPhone = new PhoneNumberValidation().validate(phoneNumber);//checks if new phone number is valid
                    if(checkPhone == true)
                    {
                        if(!tfEmail.getText().isEmpty() && tfEmail.getText().contains("@") || tfEmail.getText().isEmpty())
                        {
                            try {
                                 contact = new Contact(tfFirstName.getText(),tfLastName.getText(),phoneNumber,tfAddress.getText(),gender,tfEmail.getText(),jcType.getSelectedItem().toString());
                                 for(int i=0; i<list.size();i++)
                                 {
                                     if(list.get(i).getPhoneNumber().equalsIgnoreCase(phoneNumber))
                                     {
                                         found=true;
                                         break;
                                     }
                                 }
                                 if(found==true)
                                 {
                                    JOptionPane.showMessageDialog(null,"duplicate Phone number,please try again","Error",JOptionPane.INFORMATION_MESSAGE,icon); 
                                 }
                                 else
                                 {
                                     list.add(contact);
                                 }
                                 this.dispose();
                                 new First().setVisible(true);
                                }
                            catch(NumberFormatException ne1) {
                                        JOptionPane.showMessageDialog(null,"Invalid number, please try again","Error",JOptionPane.INFORMATION_MESSAGE,icon);

                                }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"Invalid Email, please try again","Error",JOptionPane.INFORMATION_MESSAGE,icon);
                        }
                    }
                    else
                    {
                       JOptionPane.showMessageDialog(null,"Invalid number, please try again","Error",JOptionPane.INFORMATION_MESSAGE,icon);
                    }
                }//end of if check
            }
            else
            {
                phoneNumber = jcAreaCode.getSelectedItem() + tfNumber.getText() ;
                checkPhone = new PhoneNumberValidation().validate(phoneNumber);//checks if new phone number is valid
                if(checkPhone == true)
                {
                    if(tfEmail.getText().contains("@"))
                    {
                    try {
                         contact = new Contact(tfFirstName.getText(),tfLastName.getText(),phoneNumber,tfAddress.getText(),gender,tfEmail.getText(),jcType.getSelectedItem().toString());
                         for(int i=0; i<list.size();i++)
                             {
                                 if(list.get(i).getPhoneNumber().equalsIgnoreCase(phoneNumber))
                                 {
                                     found=true;
                                     break;
                                 }
                             }
                             if(found==true)
                             {
                                JOptionPane.showMessageDialog(null,"duplicate Phone number,please try again","Error",JOptionPane.INFORMATION_MESSAGE,icon); 
                             }
                             else
                             {
                                 list.add(contact);
                             }
                         this.dispose();
                         new First().setVisible(true);
                        }
                        catch(NumberFormatException ne1) {
                                JOptionPane.showMessageDialog(null,"Invalid number, please try again","Error",JOptionPane.INFORMATION_MESSAGE,icon);

                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Invalid Email, please try again","Error",JOptionPane.INFORMATION_MESSAGE,icon);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Invalid number, please try again","Error",JOptionPane.INFORMATION_MESSAGE,icon);
                }
            }
    }//GEN-LAST:event_jbSaveActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        this.dispose();
        new AddFrame().setVisible(true);
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jLExitSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseClicked
        this.setVisible(false);
        new First().setVisible(true);
    }//GEN-LAST:event_jLExitSignMouseClicked

    private void jLExitSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseEntered
        setColor(jPanel3);
    }//GEN-LAST:event_jLExitSignMouseEntered

    private void jLExitSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseExited
        resetColor(jPanel3);
    }//GEN-LAST:event_jLExitSignMouseExited

    private void jLMinimizeSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLMinimizeSignMouseClicked

    private void jLMinimizeSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseEntered
        setColor(jPanel4);
    }//GEN-LAST:event_jLMinimizeSignMouseEntered

    private void jLMinimizeSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseExited
        resetColor(jPanel4);
    }//GEN-LAST:event_jLMinimizeSignMouseExited
    static int xx,yy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLAddress;
    private javax.swing.JLabel jLContactType;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLExitSign;
    private javax.swing.JLabel jLFirstName;
    private javax.swing.JLabel jLFrameName;
    private javax.swing.JLabel jLGender;
    private javax.swing.JLabel jLLastName;
    private javax.swing.JLabel jLMinimizeSign;
    private javax.swing.JLabel jLPhoneNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbSave;
    private javax.swing.JComboBox jcAreaCode;
    private javax.swing.JComboBox jcType;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JTextField tfNumber;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Phone.png")));
    }
}
