/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonebook;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class First extends javax.swing.JFrame {

	/*
	 * Launch the application.
	 */

	

	/**
	 * Create the application.
	 */

    public First() {
        initComponents();
        setIcon();
        
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLWelcomeToPhoneBookList = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLLogo = new javax.swing.JLabel();
        JBSearchContact = new javax.swing.JButton();
        JBAddNewContact = new javax.swing.JButton();
        JBViewAll = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLExitSign = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLMinimizeSign = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("PropSheet.disabledForeground"));
        setBounds(new java.awt.Rectangle(100, 100, 499, 361));
        setForeground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(499, 361));
        setName("frame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLWelcomeToPhoneBookList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLWelcomeToPhoneBookList.setForeground(new java.awt.Color(255, 153, 0));
        jLWelcomeToPhoneBookList.setText("Welcome To Phonebook List");
        getContentPane().add(jLWelcomeToPhoneBookList, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 260, 28));

        jPanel1.setBackground(new java.awt.Color(90, 85, 85));
        jPanel1.setPreferredSize(new java.awt.Dimension(499, 361));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLLogo.setBackground(new java.awt.Color(102, 102, 102));
        jLLogo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonebook/Phone.png"))); // NOI18N

        JBSearchContact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JBSearchContact.setText("Search Contact");
        JBSearchContact.setActionCommand("btnPush");
        JBSearchContact.setMargin(JBAddNewContact.getMargin());
        JBSearchContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSearchContactActionPerformed(evt);
            }
        });

        JBAddNewContact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JBAddNewContact.setText("Add New Contact");
        JBAddNewContact.setActionCommand("btnPush");
        JBAddNewContact.setMargin(JBAddNewContact.getMargin());
        JBAddNewContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAddNewContactActionPerformed(evt);
            }
        });

        JBViewAll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JBViewAll.setText("View All");
        JBViewAll.setActionCommand("btnPush");
        JBViewAll.setMargin(JBAddNewContact.getMargin());
        JBViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBViewAllActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(90, 85, 85));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(15, 25));

        jLExitSign.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLExitSign.setForeground(new java.awt.Color(153, 255, 255));
        jLExitSign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLExitSign.setText("x");
        jLExitSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLExitSignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLExitSignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLExitSignMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLExitSign, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLExitSign, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(90, 85, 85));
        jPanel3.setAlignmentX(0.1F);
        jPanel3.setAlignmentY(0.1F);
        jPanel3.setPreferredSize(new java.awt.Dimension(32, 33));

        jLMinimizeSign.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLMinimizeSign.setForeground(new java.awt.Color(153, 255, 255));
        jLMinimizeSign.setText(" _");
        jLMinimizeSign.setAlignmentX(0.1F);
        jLMinimizeSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLMinimizeSign, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLMinimizeSign)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBSearchContact, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBAddNewContact, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JBAddNewContact, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBSearchContact, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );

        JBAddNewContact.getAccessibleContext().setAccessibleName("Print All");
        JBAddNewContact.getAccessibleContext().setAccessibleParent(JBAddNewContact);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void setColor(JPanel p)
        {
            p.setBackground(new Color(255,0,0));
        }
    public void resetColor(JPanel p1)
        {
            p1.setBackground(new Color(90,85,85));
        }
    private void JBAddNewContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAddNewContactActionPerformed
        new AddFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JBAddNewContactActionPerformed

    private void JBSearchContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSearchContactActionPerformed
        new SearchContact().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JBSearchContactActionPerformed

    private void JBViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBViewAllActionPerformed
        new ViewAll().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JBViewAllActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String file = SingeltonFileName.getInstance().getfileName();
        ToFile write = new ReadWriteToFile();
        write.saveRecords(file);
    }//GEN-LAST:event_formWindowClosing

    private void jLExitSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseEntered
        setColor(jPanel2);
    }//GEN-LAST:event_jLExitSignMouseEntered

    private void jLExitSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseExited
        resetColor(jPanel2);
    }//GEN-LAST:event_jLExitSignMouseExited

    private void jLExitSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseClicked
        String file = SingeltonFileName.getInstance().getfileName();
        ToFile write = new ReadWriteToFile();
        write.saveRecords(file);
        System.exit(0);
    }//GEN-LAST:event_jLExitSignMouseClicked
    static int xx,yy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
       xx = evt.getX();
       yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLMinimizeSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseEntered
        setColor(jPanel3);
    }//GEN-LAST:event_jLMinimizeSignMouseEntered

    private void jLMinimizeSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseExited
        resetColor(jPanel3);
    }//GEN-LAST:event_jLMinimizeSignMouseExited

    private void jLMinimizeSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLMinimizeSignMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        String filename = SingeltonFileName.getInstance().getfileName();
        ArrayList<Contact> list = ContactListSingelton.getInstance().getArray();
        File file = new File(filename);    
        if(!file.exists()){
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(First.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            InsertToArrayFromFile insert = new InsertToArrayFromFile();
            insert.InsertToArrayFromFile(filename);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBAddNewContact;
    public javax.swing.JButton JBSearchContact;
    public javax.swing.JButton JBViewAll;
    private javax.swing.JLabel jLExitSign;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLMinimizeSign;
    private javax.swing.JLabel jLWelcomeToPhoneBookList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Phone.png")));
    }
	
}
