/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonebook;


import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLUserName = new javax.swing.JLabel();
        jLPassword = new javax.swing.JLabel();
        jTextUser = new javax.swing.JTextField();
        jbLogin = new javax.swing.JButton();
        jbRegister = new javax.swing.JButton();
        jbReset = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLWelcomePleaseSignIn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLExitSign = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLMinimizeSign = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLUserName.setForeground(new java.awt.Color(204, 255, 255));
        jLUserName.setText("User Name");
        getContentPane().add(jLUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 124, 77, 26));

        jLPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLPassword.setForeground(new java.awt.Color(204, 255, 255));
        jLPassword.setText("Password");
        getContentPane().add(jLPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 168, 77, 27));
        getContentPane().add(jTextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 128, 171, -1));

        jbLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbLogin.setText("Login");
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 226, 89, 31));

        jbRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbRegister.setText("Register");
        jbRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jbRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 226, 93, 31));

        jbReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbReset.setText("Reset");
        jbReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbResetActionPerformed(evt);
            }
        });
        getContentPane().add(jbReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 226, 106, 30));

        jPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 172, 171, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLWelcomePleaseSignIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLWelcomePleaseSignIn.setForeground(new java.awt.Color(255, 204, 0));
        jLWelcomePleaseSignIn.setText("Welcome, Please sign in");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(15, 25));

        jLExitSign.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLExitSign.setForeground(new java.awt.Color(153, 255, 255));
        jLExitSign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLExitSign.setText("x");
        jLExitSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLExitSignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLExitSignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLExitSignMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLExitSign, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLExitSign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setAlignmentX(0.1F);
        jPanel4.setAlignmentY(0.1F);
        jPanel4.setPreferredSize(new java.awt.Dimension(32, 33));

        jLMinimizeSign.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLMinimizeSign.setForeground(new java.awt.Color(153, 255, 255));
        jLMinimizeSign.setText("_");
        jLMinimizeSign.setAlignmentX(0.1F);
        jLMinimizeSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLMinimizeSign, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLMinimizeSign)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLWelcomePleaseSignIn)
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(358, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(336, 336, 336)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLWelcomePleaseSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(267, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(267, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setColor(JPanel p)
        {
            p.setBackground(new Color(255,0,0));
        }
    public void resetColor(JPanel p1)
        {
            p1.setBackground(new Color(102,102,102));
        }
    private void jbRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegisterActionPerformed
        new RegisterPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbRegisterActionPerformed

    private void jbResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbResetActionPerformed
        jTextUser.setText(null);
        jPassword.setText(null);
    }//GEN-LAST:event_jbResetActionPerformed

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        UserInfo tempUser = new UserInfo() ;
        ImageIcon icon = new ImageIcon(getClass().getResource("phoneIcon.png"));
        tempUser.setUserName(jTextUser.getText());
        tempUser.setPassword(jPassword.getText());
        File file = new File("User.txt");
        if(!file.exists()){   //checks if users file exists, if not, then there are no users in the DataBase
            JOptionPane.showMessageDialog(null, "You need to register before use","Error",JOptionPane.INFORMATION_MESSAGE,icon);
        }
        else   //if yes, then need to check if the user info exists in the users file
        {
            new CheckUser().checkFile(tempUser, "User.txt");
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbLoginActionPerformed

    private void jLExitSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLExitSignMouseClicked

    private void jLExitSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseEntered
        setColor(jPanel3);
    }//GEN-LAST:event_jLExitSignMouseEntered

    private void jLExitSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseExited
        resetColor(jPanel3);
    }//GEN-LAST:event_jLExitSignMouseExited

    private void jLMinimizeSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLMinimizeSignMouseClicked

    private void jLMinimizeSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseEntered
        setColor(jPanel4);
    }//GEN-LAST:event_jLMinimizeSignMouseEntered

    private void jLMinimizeSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseExited
        resetColor(jPanel4);
    }//GEN-LAST:event_jLMinimizeSignMouseExited

    static int xx,yy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLExitSign;
    private javax.swing.JLabel jLMinimizeSign;
    private javax.swing.JLabel jLPassword;
    private javax.swing.JLabel jLUserName;
    private javax.swing.JLabel jLWelcomePleaseSignIn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextUser;
    private javax.swing.JButton jbLogin;
    private javax.swing.JButton jbRegister;
    private javax.swing.JButton jbReset;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Phone.png")));
    }
}
