/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonebook;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLRegistration = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLExitSign = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLMinimizeSign = new javax.swing.JLabel();
        jLMinimum6Characters1 = new javax.swing.JLabel();
        jPasswordConfirmation = new javax.swing.JPasswordField();
        jLConfirmPassword = new javax.swing.JLabel();
        jBSave = new javax.swing.JButton();
        jbReset = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jLPassword = new javax.swing.JLabel();
        jTextUserName = new javax.swing.JTextField();
        jLUserName = new javax.swing.JLabel();
        jLMinimum6Characters2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLRegistration.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLRegistration.setForeground(new java.awt.Color(255, 204, 0));
        jLRegistration.setText("Registration");
        getContentPane().add(jLRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 190, 30));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(15, 25));

        jLExitSign.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLExitSign.setForeground(new java.awt.Color(153, 255, 255));
        jLExitSign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLExitSign.setText("x");
        jLExitSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLExitSignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLExitSignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLExitSignMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLExitSign, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLExitSign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setAlignmentX(0.1F);
        jPanel4.setAlignmentY(0.1F);
        jPanel4.setPreferredSize(new java.awt.Dimension(32, 33));

        jLMinimizeSign.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLMinimizeSign.setForeground(new java.awt.Color(153, 255, 255));
        jLMinimizeSign.setText("_");
        jLMinimizeSign.setAlignmentX(0.1F);
        jLMinimizeSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLMinimizeSign, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLMinimizeSign)
        );

        jLMinimum6Characters1.setForeground(new java.awt.Color(255, 153, 0));
        jLMinimum6Characters1.setText("minimum of 6 characters");

        jLConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLConfirmPassword.setForeground(new java.awt.Color(204, 255, 255));
        jLConfirmPassword.setText("Confirm Password");

        jBSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBSave.setText("Save");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jbReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbReset.setText("Reset");
        jbReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbResetActionPerformed(evt);
            }
        });

        jBCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBCancel.setText("Cancel");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        jLPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLPassword.setForeground(new java.awt.Color(204, 255, 255));
        jLPassword.setText("Password");

        jLUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLUserName.setForeground(new java.awt.Color(204, 255, 255));
        jLUserName.setText("User Name");

        jLMinimum6Characters2.setForeground(new java.awt.Color(255, 153, 0));
        jLMinimum6Characters2.setText("minimum of 6 characters");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jBSave, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbReset, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jBCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLMinimum6Characters2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTextUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLConfirmPassword)
                        .addGap(4, 4, 4)
                        .addComponent(jPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLMinimum6Characters1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(358, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(340, 340, 340)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLMinimum6Characters1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jLMinimum6Characters2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(267, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(267, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setColor(JPanel p)
        {
            p.setBackground(new Color(255,0,0));
        }
    public void resetColor(JPanel p1)
        {
            p1.setBackground(new Color(102,102,102));
        }
    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        this.setVisible(false);
        new LoginPage().setVisible(true);
        
    }//GEN-LAST:event_jBCancelActionPerformed

    private void jbResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbResetActionPerformed
        jTextUserName.setText(null);
        jPassword.setText(null);
        jPasswordConfirmation.setText(null);
    }//GEN-LAST:event_jbResetActionPerformed

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        UserInfo tempUser = new UserInfo() ;  
        ImageIcon icon = new ImageIcon(getClass().getResource("phoneIcon.png"));
        boolean check;
        boolean checkInfo;
        checkInfo = new PasswordAndNameValidation().validate(jTextUserName.getText(), "UserName"); //check if the username exists in the DataBase
        if(checkInfo == false)
        {
            checkInfo = new PasswordAndNameValidation().validate(jPassword.getText(), "Password");
            if(checkInfo == false)
            {
                if(jPassword.getText().equals(jPasswordConfirmation.getText()))
                {
                    //check if exist
                    check = new CheckIfExist().readFile(jTextUserName.getText(), "User.txt");
                    if(check == true)
                    {
                        JOptionPane.showMessageDialog(null, "This USERNAME is already exist, Please choose a differnt USERNAME","Error",JOptionPane.INFORMATION_MESSAGE,icon);
                        jTextUserName.setText(null);
                        jPassword.setText(null);
                        jPasswordConfirmation.setText(null);
                    }
                    else  //username do not exist in the DataBase
                    {
                        tempUser.setUserName(jTextUserName.getText());
                        tempUser.setPassword(jPassword.getText());
                        ToFile open = new UserNameFile();
                        open.saveRecords("User.txt",tempUser); //adds the new user to the DataBase
                        this.setVisible(false);
                        new LoginPage().setVisible(true);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"passwords fields must be the same","Error",JOptionPane.INFORMATION_MESSAGE,icon);
                }
            }
        }
    }//GEN-LAST:event_jBSaveActionPerformed

    private void jLExitSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseClicked
        this.setVisible(false);
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_jLExitSignMouseClicked

    private void jLExitSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseEntered
        setColor(jPanel3);
    }//GEN-LAST:event_jLExitSignMouseEntered

    private void jLExitSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseExited
        resetColor(jPanel3);
    }//GEN-LAST:event_jLExitSignMouseExited

    private void jLMinimizeSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLMinimizeSignMouseClicked

    private void jLMinimizeSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseEntered
        setColor(jPanel4);
    }//GEN-LAST:event_jLMinimizeSignMouseEntered

    private void jLMinimizeSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseExited
        resetColor(jPanel4);
    }//GEN-LAST:event_jLMinimizeSignMouseExited

    static int xx,yy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        File file = new File("User.txt");
        if(!file.exists()){
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(First.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBSave;
    private javax.swing.JLabel jLConfirmPassword;
    private javax.swing.JLabel jLExitSign;
    private javax.swing.JLabel jLMinimizeSign;
    private javax.swing.JLabel jLMinimum6Characters1;
    private javax.swing.JLabel jLMinimum6Characters2;
    private javax.swing.JLabel jLPassword;
    private javax.swing.JLabel jLRegistration;
    private javax.swing.JLabel jLUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JPasswordField jPasswordConfirmation;
    private javax.swing.JTextField jTextUserName;
    private javax.swing.JButton jbReset;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Phone.png")));
    }
}
