/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonebook;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ViewAll extends javax.swing.JFrame {
    public Contact tempContact = new Contact();
    private static Scanner x;
    ArrayList<Contact> list = ContactListSingelton.getInstance().getArray();
    
    /**
     * Creates new form ViewAll
     */
    public ViewAll() {
        initComponents();
        setIcon();
         AddtoTable();
    }
    public void AddtoTable() //adds to a table ,all the contacts from the contact array
    {
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
         Collections.sort(list, Contact.FirstNameComparator);
        for (Contact list1 : list) {
            tempContact = list1;
            model.addRow(new Object[]{tempContact.getFirstName(),tempContact.getLastName(),tempContact.getPhoneNumber(),tempContact.getAddress(),tempContact.getSex(),tempContact.getEmailAddress(),tempContact.getContactType()});
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Panel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLExitSign = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLMinimizeSign = new javax.swing.JLabel();
        jbDelete = new javax.swing.JButton();
        jbHome = new javax.swing.JButton();
        jrLastName = new javax.swing.JRadioButton();
        jrFirstName = new javax.swing.JRadioButton();
        jLSortBy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(607, 360));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Phone Number", "Address", "Gender", "Email", "Contact Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 860, 340));

        Panel1.setBackground(new java.awt.Color(102, 102, 102));
        Panel1.setPreferredSize(new java.awt.Dimension(900, 500));
        Panel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel1MouseDragged(evt);
            }
        });
        Panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel1MousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(15, 25));

        jLExitSign.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLExitSign.setForeground(new java.awt.Color(153, 255, 255));
        jLExitSign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLExitSign.setText("x");
        jLExitSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLExitSignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLExitSignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLExitSignMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLExitSign, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLExitSign, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setAlignmentX(0.1F);
        jPanel3.setAlignmentY(0.1F);
        jPanel3.setPreferredSize(new java.awt.Dimension(32, 33));

        jLMinimizeSign.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLMinimizeSign.setForeground(new java.awt.Color(153, 255, 255));
        jLMinimizeSign.setText("_");
        jLMinimizeSign.setAlignmentX(0.1F);
        jLMinimizeSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLMinimizeSignMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLMinimizeSign, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLMinimizeSign)
        );

        jbDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbDelete.setText("Delete Contact");
        jbDelete.setActionCommand("btnPush");
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });

        jbHome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbHome.setText("Home Page");
        jbHome.setActionCommand("btnPush");
        jbHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHomeActionPerformed(evt);
            }
        });

        jrLastName.setBackground(new java.awt.Color(102, 102, 102));
        jrLastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrLastName.setForeground(new java.awt.Color(204, 255, 255));
        jrLastName.setText("Last Name");
        jrLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrLastNameActionPerformed(evt);
            }
        });

        jrFirstName.setBackground(new java.awt.Color(102, 102, 102));
        jrFirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrFirstName.setForeground(new java.awt.Color(204, 255, 255));
        jrFirstName.setSelected(true);
        jrFirstName.setText("First Name");
        jrFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrFirstNameActionPerformed(evt);
            }
        });

        jLSortBy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLSortBy.setForeground(new java.awt.Color(255, 204, 0));
        jLSortBy.setText("Sort By");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jrFirstName)
                .addGap(31, 31, 31)
                .addComponent(jrLastName)
                .addGap(245, 245, 245)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
            .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                    .addContainerGap(858, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrFirstName)
                            .addComponent(jrLastName))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(467, Short.MAX_VALUE)))
        );

        getContentPane().add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void setColor(JPanel p)
        {
            p.setBackground(new Color(255,0,0));
        }
    public void resetColor(JPanel p1)
        {
            p1.setBackground(new Color(102,102,102));
        }
    private void jbHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHomeActionPerformed
   
        this.setVisible(false);
        new First().setVisible(true);
    }//GEN-LAST:event_jbHomeActionPerformed

    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
        //remove a contact from the table and from the contact array
        ImageIcon icon = new ImageIcon(getClass().getResource("phoneIcon.png"));
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        int row= -1;
        row = jTable1.getSelectedRow();
        if (row!= -1)
        {
            Contact contactToRemove = new Contact();
            contactToRemove.setFirstName(jTable1.getModel().getValueAt(row, 0).toString());
            contactToRemove.setLastName(jTable1.getModel().getValueAt(row, 1).toString());
            contactToRemove.setPhoneNumber(jTable1.getModel().getValueAt(row, 2).toString());
            contactToRemove.setAddress(jTable1.getModel().getValueAt(row, 3).toString());
            contactToRemove.setSex(jTable1.getModel().getValueAt(row, 4).toString());
            contactToRemove.setEmailAddress(jTable1.getModel().getValueAt(row, 5).toString());
            contactToRemove.setContactType(jTable1.getModel().getValueAt(row, 6).toString());
            Contact new_contact=new Contact(contactToRemove.getFirstName(),contactToRemove.getLastName(),contactToRemove.getPhoneNumber(),contactToRemove.getAddress(),contactToRemove.getSex(),contactToRemove.getEmailAddress(),contactToRemove.getContactType());
            int check = JOptionPane.showConfirmDialog(null, "You have choosen to DELETE a contact, are you sure?","Delete Contact",JOptionPane.YES_NO_OPTION);
            if (check == 0)
            {

                model.removeRow(row);
                for(int i=0;i<list.size();i++)
                {
                    if(list.get(i).getPhoneNumber().equals(new_contact.getPhoneNumber()))
                        list.remove(i);
                }
            }
            else
           {
               JOptionPane.showMessageDialog(null, "Thank you for not deleting","Deletion Canceled",JOptionPane.INFORMATION_MESSAGE,icon);
           }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error! you must choose a contact from the table","Error",JOptionPane.INFORMATION_MESSAGE,icon); 
        }
        
    }//GEN-LAST:event_jbDeleteActionPerformed

    private void jrFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrFirstNameActionPerformed
        //sort the contacts in the table by first name
        if (jrFirstName.isSelected())
        {
            jrLastName.setSelected(false);
            jTable1.setModel(new DefaultTableModel (null,new Object[]{"First Name","Last Name","Phone Number","Address","Gender","Email","Contact Type"}));
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            Collections.sort(list, Contact.FirstNameComparator);
            Contact tempcontact=new Contact();
        for (Contact list1 : list) {
            tempContact = list1;
            model.addRow(new Object[]{tempContact.getFirstName(),tempContact.getLastName(),tempContact.getPhoneNumber(),tempContact.getAddress(),tempContact.getSex(),tempContact.getEmailAddress(),tempContact.getContactType()});
        }
        }
    }//GEN-LAST:event_jrFirstNameActionPerformed

    private void jrLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrLastNameActionPerformed
        //sort the contacts in the table by last name
        if(jrLastName.isSelected())
        {
            jrFirstName.setSelected(false);
            jTable1.setModel(new DefaultTableModel (null,new Object[]{"First Name","Last Name","Phone Number","Address","Gender","Email","Contact Type"}));
           DefaultTableModel model1 = (DefaultTableModel)jTable1.getModel();
           Collections.sort(list, Contact.LastNameComparator);
           Contact tempcontact=new Contact();
        for (Contact list1 : list) {
            tempContact = list1;
            model1.addRow(new Object[]{tempContact.getFirstName(),tempContact.getLastName(),tempContact.getPhoneNumber(),tempContact.getAddress(),tempContact.getSex(),tempContact.getEmailAddress(),tempContact.getContactType()});
        }
        }
            
    }//GEN-LAST:event_jrLastNameActionPerformed

    private void jLExitSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseClicked
        this.setVisible(false);
        new First().setVisible(true);
    }//GEN-LAST:event_jLExitSignMouseClicked

    private void jLExitSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseEntered
        setColor(jPanel2);
    }//GEN-LAST:event_jLExitSignMouseEntered

    private void jLExitSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLExitSignMouseExited
        resetColor(jPanel2);
    }//GEN-LAST:event_jLExitSignMouseExited

    private void jLMinimizeSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLMinimizeSignMouseClicked

    private void jLMinimizeSignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseEntered
        setColor(jPanel3);
    }//GEN-LAST:event_jLMinimizeSignMouseEntered

    private void jLMinimizeSignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMinimizeSignMouseExited
        resetColor(jPanel3);
    }//GEN-LAST:event_jLMinimizeSignMouseExited
    static int xx,yy;
    private void Panel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_Panel1MousePressed

    private void Panel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_Panel1MouseDragged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //show contact info in a pop-up
        int row = jTable1.getSelectedRow();
        String msg = "First Name : "+ jTable1.getModel().getValueAt(row, 0).toString()+
                     "\nLast Name : " +jTable1.getModel().getValueAt(row, 1).toString()+
                     "\nPhone Number : "+jTable1.getModel().getValueAt(row, 2).toString()+
                     "\nAddress : "+jTable1.getModel().getValueAt(row, 3).toString()+
                     "\nGender : "+jTable1.getModel().getValueAt(row, 4).toString()+
                     "\nEmail : "+jTable1.getModel().getValueAt(row, 5).toString()+
                     "\nContact Type : "+jTable1.getModel().getValueAt(row, 6).toString();
        ImageIcon icon = new ImageIcon(getClass().getResource("phoneIcon.png"));
        JOptionPane.showMessageDialog(null,  msg,"Contact Info", JOptionPane.INFORMATION_MESSAGE, icon);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JLabel jLExitSign;
    private javax.swing.JLabel jLMinimizeSign;
    private javax.swing.JLabel jLSortBy;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JButton jbDelete;
    public javax.swing.JButton jbHome;
    private javax.swing.JRadioButton jrFirstName;
    private javax.swing.JRadioButton jrLastName;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Phone.png")));
    }
}
